### ISSUE TITLE
Lỗi cắt chức trong module

### ISSUE THREAD

**Issue by vuthao** [nukeviet/module-videoclips#10]
Hiện tại module này đang cắt chữ rất tùy tiện.

Cần sửa lại để có thể cấu hình vào quản trị tính năng cắt chữ này.

![screen shot 2017-09-26 at 17 12 02](https://user-images.githubusercontent.com/2491500/30855107-fa6ca066-a2dd-11e7-9b22-a9e2bb88a28e.png)

**Comment by ThinhNguyenVB** [comment]
Em đã chuyển đổi vào config của module và đã fix tại đây: https://github.com/nukeviet/module-videoclips/pull/11/commits/8e2f4958995176f696fcf8304be9d888d79c940c
