### ISSUE TITLE
Lỗi khi lưu và hiển thị toàn bộ tin tức - chi tiết

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-videoclips#20]
Trong mô-đun, khi bạn cố gắng điền đầy đủ tin tức, bạn nhận được một thông báo lỗi, nhưng nó được ghi lại. Khi trang web hiển thị liên kết dưới tin ngắn - xem thêm chi tiết, nhưng kết quả của các tin chi tiết không được thực hiện.

**Comment by hoaquynhtim99** [comment]
@NukeVlad mô tả rõ hơn lỗi này xem sao, mình đọc không hiểu.

**Comment by NukeVlad** [comment]
@hoaquynhtim99  Có một nội dung ngắn gọn và đầy đủ nội dung. Nội dung đầy đủ không được ghi lại

**Comment by hoaquynhtim99** [comment]
Mình test thấy lưu bình thường

**Comment by NukeVlad** [comment]
Có lẽ lỗi ở phía tôi, tôi có một tin tức hoàn toàn không được sao chép lại trên trang
