### ISSUE TITLE
Lỗi phân trang module videoclips

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-videoclips#21]
Hiện tại khi chuyển sang page thứ 2 mà có 1 video thì lại lấy hết dữ liệu của page 1 như vậy là không đúng Lỗi ở:
- main
- topic

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-videoclips/commit/53db611ddc1c278b4f53a2e6b4da68649ef94a81
