### ISSUE TITLE
số lần xem

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-videoclips#22]
Trong bảng quản trị trong phần danh sách video, bạn phải thêm hàng lượt xem cho nội dung thông tin: số lượt xem, số ý kiến, số thẻ

**Comment by hoaquynhtim99** [comment]
Đã thêm https://github.com/nukeviet/module-videoclips/commit/01e8db51023eac95a31249f25bc9c3c4b6ee39c6
