### ISSUE TITLE
Thêm cách trình bày module video và theo bootstrap

### ISSUE THREAD

**Issue by ThinhNguyenVB** [nukeviet/module-videoclips#24]
Hiện tại module video đang chỉ có một cách sắp xếp đơn thuần là hiển thị tất cả các video và danh mục phía trên.
Mình đề xuất thêm cách trình bày như kiểu sau và sẽ lấy luôn ảnh thumbnail nếu là video youtube thay vì phải import ảnh thumbnail và sẽ fix vấn đề phân trang ở giao diện ban đầu hiện có và sẽ sử dụng bootstrap và bỏ cách trình bày như hiện tại do không dùng boostrap
![image](https://user-images.githubusercontent.com/13896524/35562523-37d68cd0-05e6-11e8-91ab-70da2214d652.png)

**Comment by NukeVlad** [comment]
Vâng, điều đó sẽ tốt hơn

**Comment by hoaquynhtim99** [comment]
Module mới nhất viết lại phần này a nhé
