### ISSUE TITLE
url cuối không phải là .html

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-videoclips#25]
Tại sao URL video chính có kết thúc dưới dạng một dòng xiên "/", thay vì .html

**Comment by NukeVlad** [comment]
Trợ giúp, xin vui lòng, sự giúp đỡ của bạn là rất cần thiết. Tôi sử dụng Phát lại mô-đun của phiên bản video clip '=>' 4.3.00 '. name' => 'Videoclips'. Có sự cố trong quá trình tạo URL, kết thúc bằng "/" thay vì ".html".
Như tôi đã hiểu, không có tham số nào trong việc tạo URL trong một hàng. $ global_config ['rewrite_exturl']

**Comment by NukeVlad** [comment]
Tôi đã quản lý để sửa lỗi. Trong một số tệp mô-đun ở cuối dòng tạo URL sau . $row['alias'] tôi đã thêm . $global_config['rewrite_exturl']

**Comment by hoaquynhtim99** [comment]
Fixed https://github.com/nukeviet/module-videoclips/commit/6465cae4daccca8c967897f0b9ff13f077d88800
