### ISSUE TITLE
MODULE PLAYBACK OF VIDEO-CLIPS PHÂN TRANG TRANG KHÔNG HỢP LỆ

### ISSUE THREAD

**Issue by NukeVlad** [nukeviet/module-videoclips#26]
@hoaquynhtim99 Trên ví dụ về trang web của tôi, tôi mang hình ảnh. Hệ thống đã chia các bài viết thành 2 trang, nhưng trang thứ hai không hiển thị tất cả các video. Nếu tôi thay đổi số trong URL và tôi chỉ định 4 thay vì 2, thì video bị thiếu sẽ xuất hiện. https://nukeviet.vn/vi/forum/Module-playback-of-video-clips-phan-trang-trang-khong-hop-le-t44907-p189665/#p189665

**Comment by NukeVlad** [comment]
Tại sao tôi không có quyền truy cập để chỉnh sửa?

**Comment by ThinhNguyenVB** [comment]
@NukeVlad bạn phải pull project về rồi bạn sửa sau đó push lên rồi chuyển dữ liệu sang nhánh chính. Phần phân trang này mình sẽ xem xét lại trong danh sách sửa lại toàn bộ module này vì nhiều cái bất cập so với nhu cầu hiện tại

**Comment by NukeVlad** [comment]
ThinhNguyenVB Cảm ơn bạn. Phân trang đã được sửa nhưng thiếu trong bản cập nhật

**Comment by hoaquynhtim99** [comment]
@NukeVlad check trên bản mới nhất nhé cái này hình như đã fix lâu rồi
