### ISSUE TITLE
Loại bỏ các tính năng không cần thiết !

### ISSUE THREAD

**Issue by billygoat-trump** [nukeviet/module-videoclips#41]
[không phải báo lỗi là báo hỗ trợ sử dụng] Như tiêu đề, cần tinh chỉnh lại các tính năng thừa của Jwplayer khi trình chiếu lại video trên youtube.com -> như loại bỏ "Watch on Youtube.com" bên góc trái ... trước có biết kỹ thuật này ở đâu đó, nhưng không dùng nhiều năm nay chỉ biết hỏi.
?rel=0&controls=1&autohide=2&modestbranding=1&showinfo=0; frameborder="0"
code này không loại bỏ SẠCH cái "Watch on Youtube" bên góc trái
Cám ơn nhiều !

**Comment by hoaquynhtim99** [comment]
Module này đối với youtube thì dùng iframe chứ không dùng jwplayer để phát bạn.
Ẩn cái đó đi thì nó ẩn luôn cả các nút công cụ https://www.youtube.com/embed/UcVWjQxdlow?controls=0
Còn jwplayer module này chỉ dùng bản sạch không có tùy chỉnh.
