### ISSUE TITLE
Vấn đề đặt các file css và font

### ISSUE THREAD

**Issue by hoaquynhtim99** [nukeviet/module-videoclips#8]
Hiện tại có một số file đang đặt như sau

```
themes/default/css/flexslider.css
themes/default/css/fonts/*
themes/default/js/jquery.flexslider.js
```

Các file này khi đóng gói sẽ không được đóng gói cũng như việc sao chép giao diện để làm cho các giao diện khác sẽ gây sót file cũng như thừa file khi xóa module khỏi hệ thống.

Liệu có nên di chuyển chúng sang cấu trúc như của jwplayer đang đặt:

```
themes/default/images/videoclips/jwplayer/*
```

**Comment by vuthao** [comment]
@hoaquynhtim99 Làm như em đề nghị đi.
